### ISSUE TITLE
result.getHttpStatus() equals  NETWORK_ERROR .

### ISSUE THREAD

**Issue by savicprvoslav** [pusher/pusher-http-java#1]
Hello, 
 we use pusher java api and if we send requests in this order:

req1
req2
req3
<--------- here we make a pause for 3 minutes
req4  <---  here result.getHttpStatus() equals  NETWORK_ERROR .
----------

This is huge bug as we can not use your service.

**Comment by zimbatm** [comment]
Hi @savicprvoslav,

It's possible for network errors to happen but it shouldn't be systematic. If that happens all the time it could be an issue in the code, or anything between your server and our servers. I'm not really to understand what's happening in your code from the example you gave. If you want to share more details we can continue the conversation at support@pusher.com . Otherwise a good start would be to give me the value of result.getMessage() and if possible a small reproductible sample.

Best

**Comment by savicprvoslav** [comment]
Hello, 
 i will send you the code in the morning .

**Comment by savicprvoslav** [comment]
Here is the code, 
 you can see the call and the log. We are currently using Sandbox plan. If you require id of the account i will send you that privately .

Thank you for your help.
```java
pusher = new Pusher(appId, apiKey, apiSecret);

					Result result = pusher.trigger(pusherPojo.getChanels(),
							pusherPojo.getEventName(), pusherPojo.getData()
									.toString());

					LOGGER.debug( result.getHttpStatus()
							+ " " + result.getStatus() + " "
							+ result.getStatus() + " " + result.getMessage());

```



```java
null NETWORK_ERROR NETWORK_ERROR org.apache.http.NoHttpResponseException: api.pusherapp.com:80 failed to respond
```

**Comment by zimbatm** [comment]
Thanks,

I don't see anything obvious. Is it possible that api.pusherapp.com is not reachable because of firewall ? Can you give me the output of `curl -v http://api.pusherapp.com/` run from the same machine where the code is executed ?

**Comment by savicprvoslav** [comment]
This also happens on my local win machine.



```
root@api1:~# curl -v http://api.pusherapp.com/
* Hostname was NOT found in DNS cache
*   Trying 184.73.245.186...
* Connected to api.pusherapp.com (184.73.245.186) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.pusherapp.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=utf-8
* Server thin is not blacklisted
< Server: thin
< Content-Length: 11
< Connection: keep-alive
<
Pusher API
* Connection #0 to host api.pusherapp.com left intact
```

**Comment by savicprvoslav** [comment]
@zimbatm Does this curl result help you ?

Thank you.

**Comment by zimbatm** [comment]
Thanks, I tried reproducing the issue locally but everything's working fine here. Would you be able to capture a tcpdump of the network activity ?

**Comment by mojsilo** [comment]
Would you mind tell us what did you do in order to make it work?

**Comment by sford** [comment]
I am sure everyone has probably moved on from this issue, but just in case someone else runs into this, try adjusting HttpClient pool max times:

```
		HttpClientBuilder clientBuilder = Pusher.defaultHttpClientBuilder()
				.setConnectionManager(new PoolingHttpClientConnectionManager(30, TimeUnit.SECONDS));
```

I was running into pretty regular NETWORK_ERROR errors and adjusting the pool max times stabilized everything. It appears that HttpClient tries to keep connections around indefinitely in its pool, and problems can occur if Pusher client tries to use a connection that has already been terminated by something like the Pusher servers (http keep alive timeout hit) or a firewall.
