### ISSUE TITLE
How do you set the http port?

### ISSUE THREAD

**Issue by edwardotis** [pusher/pusher-http-java#10]
I am using a pusher-fake server for development, and I need to set a custom port so my app can send the trigger() event to the correct port of the local pusher-fake server.

In the equivalent python library, the Pusher constructor accepts an http port override. However, the port override appears to be missing from the constructor of pusher-http-java. 

https://github.com/tristandunn/pusher-fake

**Comment by zimbatm** [comment]
Hi, did you try setting the host with the port ? I'm 90% sure that it would work:
```java
Pusher pusher = new Pusher(APP_ID, KEY, SECRET);
pusher.setHost("yourhost:8080");
```

**Comment by edwardotis** [comment]
Thanks @zimbatm, that worked!
