### ISSUE TITLE
Allow 100 channels for single event trigger

### ISSUE THREAD

**Issue by bayerls** [pusher/pusher-http-java#23]
I want to send one single event to 100 different channels. The API Documentation says for the channels param:  "Array of one or more channel names - limited to 100 channels". for the endpoint:  /events (NOT batched).

But in the Pusher class there is the check Prerequisites.maxLength("channels", 10, channels); in line 340, what prevents more then 10 channels.

Is this a bug? A max length of 100 should be checked there.

**Comment by kn100** [comment]
This very well could be! I'll investigate when I get some time but feel free to make the change yourself and PR it up!
