### ISSUE TITLE
Make it possible to use custom JSON serialization

### ISSUE THREAD

**Issue by marvec** [pusher/pusher-http-java#25]
My project is JavaEE based backend. As such, it mostly uses Jackson for JSON and all objects are configured in that way. When I want to send notification to my frontend, the objects are not properly serialized because Jackson annotations are ignored. I have a theoretical possibility to set my own serialization engine (Pusher.setGsonSerializer()) but I can only provide Gson. Gson is a final class that cannot be extended. Reflection is nowadays almost out of scope. The sad thing is that only a single method is used from Gson (Gson.toJson(Object)). It is a pity that some simple generic interface is not used as a parameter in setGsonSerializer() (and a better method name here). It would be super easy to wrap Gson or anything else to it.

**Comment by jeremieca** [comment]
+1 !!!!

**Comment by kn100** [comment]
@jeremieca https://github.com/pusher/pusher-http-java/pull/26 this PR addresses this problem, I am going to merge it soon. Can you let me know if it solves your problem?

**Comment by kn100** [comment]
This is officially a feature. Thanks for your patience!
