### ISSUE TITLE
Document Java compatibility policy

### ISSUE THREAD

**Issue by hosamaly** [pusher/pusher-http-java#29]
We should decide on, and document, our policy with Java backwards-compatibility.

This project is currently set to compile into binaries that support Java 5. However, we run our tests against Java 7 and 8 (see issue #27).

Additionally, compiling against Java 5 limits us from testing against Java 9 and later because the compiler in these versions can only compile to Java 6 binaries. We can work around this limitation in the build script if necessary.

We need to document our policy for testing against different Java versions, and then update the build scripts to reflect it.

**Comment by WillSewell** [comment]
Decided in https://github.com/pusher/pusher-http-java/pull/32#issuecomment-513780873. Needs documenting.

**Comment by WillSewell** [comment]
We have defined a support policy internally. We have decided that just the versions of Java SE we currently support will be listed in the README.
