### ISSUE TITLE
Allowing non-blocking HTTP calls?

### ISSUE THREAD

**Issue by sp00m** [pusher/pusher-http-java#37]
We're thinking of using Pusher, but our codebase relies on Netty, a non-blocking web server, so if we could avoid having Pusher blocking on HTTP calls, it would be a perfect fit.

Do you have plans for this already?

Ideally, the methods would return `CompletableFuture<Result>` instead of `Result`. Backward compatibility can probably be ensured by adding new methods, e.g. keeping the existing `Result post(...)` but adding `CompletableFuture<Result> postAsync(...)`, and having the former `Result post(...)` simply call `postAsync(...).get()`.

For now, I'll run those blocking calls inside a dedicated thread pool to release the request thread, but it's more a workaround than a solution, as a thread is still being blocked at the end.

I had a quick look at this codebase, it apparently relies on Apache [HttpClient](http://hc.apache.org/httpcomponents-client-ga/index.html), which does block unfortunately. Apache provides an [Async HttpClient](http://hc.apache.org/httpcomponents-asyncclient-dev/index.html) too, but it's quite low level.

Other solutions could be [AHC](https://github.com/AsyncHttpClient/async-http-client) or [OkHttp](https://square.github.io/okhttp/), both support CompletableFutures out of the box (+1 for OkHttp personally).

I do believe this might become quite critical given the new(ish) reactive frameworks out there like Spring WebFlux or Micronaut.

What do you think?

**Comment by sp00m** [comment]
I just noticed pusher-http-java does expose Apache HttpClient's objects directly through `#configureHttpClient(...)` or `#defaultHttpClientBuilder(...)`, which will make the migration to another HTTP client library harder unfortunately... Unless we allow breaking changes.

**Comment by sp00m** [comment]
What about creating a whole new PusherAsync/Pusher2/PusherClient class based on a non-blocking Http client library, and deprecating the current Pusher class?

**Comment by sp00m** [comment]
Hey @elverkilde, this code is sitting on `master` since quite a while now, any chance to see it released sometime soon?

**Comment by mdpye** [comment]
Done, sorry for the delay! 1.2.0 released, thank for your contribution! :bow:
