### ISSUE TITLE
README indicates using 1.2.1, Maven Central's newest version is 1.2.0

### ISSUE THREAD

**Issue by Tovrik** [pusher/pusher-http-java#53]
Readme states:

```
Installation
The pusher-http-java library is available in Maven Central:

<dependency>
  <groupId>com.pusher</groupId>
  <artifactId>pusher-http-java</artifactId>
  <version>1.2.1</version>
</dependency>
```

Maven Central says that is a lie: https://mvnrepository.com/artifact/com.pusher/pusher-http-java

**Comment by elverkilde** [comment]
Hi @Tovrik , apologies for the delay, this is now released. We are working on improving the release process to avoid problems like this in the future.
