### ISSUE TITLE
Unable to send authenticated events to user

### ISSUE THREAD

**Issue by jonchay** [pusher/pusher-http-java#67]
Based on the [documentation](https://pusher.com/docs/channels/server_api/server-to-user-messages/), the Java lib is behind on supporting pushing events to authenticated users, but this functionality can be copied from the php counterpart.

However the channel validation is preventing servers from sending events due to the new naming convention:
https://github.com/pusher/pusher-http-java/blob/fbd091a3dcf611013a4e33f8cf2d06fe0e3e9983/src/main/java/com/pusher/rest/util/Prerequisites.java#L15-L17

Regex on the php codebase has been updated to support this:
https://github.com/pusher/pusher-http-php/blob/ce45184bc500c211af94a733b9e7a88dc1fdac0c/src/Pusher.php#L205-L209

**Comment by benjamin-tang-pusher** [comment]
Hi, thanks for the suggestion. We will implement sending events to authenticated users on the Java server library, but we cannot commit to a timeline for this.

I will close this github issue.

**Comment by ofloy** [comment]
@benjamin-tang-pusher Any update on this please?
I tried this with `pusher-http-node` which has a `sendToUser` function which internally calls `trigger` function from the `events` and not `pusher` object. This results in skipped validation of the channel name.
https://github.com/pusher/pusher-http-node/blob/1812cb46c204162a3119a548ba6357449cdf51b5/lib/pusher.js#L168

https://github.com/pusher/pusher-http-node/blob/1812cb46c204162a3119a548ba6357449cdf51b5/lib/events.js#L26

**Comment by Puspendert** [comment]
@benjamin-tang-pusher Any update on this please?
I tried this with `pusher-http-node` which has a `sendToUser` function which internally calls `trigger` function from the `events` and not `pusher` object. This results in skipped validation of the channel name.
https://github.com/pusher/pusher-http-node/blob/1812cb46c204162a3119a548ba6357449cdf51b5/lib/pusher.js#L168

https://github.com/pusher/pusher-http-node/blob/1812cb46c204162a3119a548ba6357449cdf51b5/lib/events.js#L26

**Comment by ofloy** [comment]
Anyways, I managed to make it work by doing a mix or node and java libraries.
```
private void sendToUsers(@NotEmpty List<String> users, @NotEmpty String event, String data){
        List<String> channels = users.stream().map("#server-to-user-%s"::formatted).collect(Collectors.toList());
        final Gson BODY_SERIALIZER = new GsonBuilder()
                .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
                .disableHtmlEscaping()
                .create(); //can be moved to instance variables
        Map<String, Object> eventBody = new HashMap<>();
        eventBody.put("name", event);
        eventBody.put("data", data);
        eventBody.put("channels", channels);
        final String body = BODY_SERIALIZER.toJson(eventBody);

        pusher.post("/events", body); //Pusher instance
    }
```

**Comment by Puspendert** [comment]
Anyways, I managed to make it work by doing a mix of node and java libraries.
```
private void sendToUsers(@NotEmpty List<String> users, @NotEmpty String event, String data){
        List<String> channels = users.stream().map("#server-to-user-%s"::formatted).collect(Collectors.toList());
        final Gson BODY_SERIALIZER = new GsonBuilder()
                .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
                .disableHtmlEscaping()
                .create(); //can be moved to instance variables
        Map<String, Object> eventBody = new HashMap<>();
        eventBody.put("name", event);
        eventBody.put("data", data);
        eventBody.put("channels", channels);
        final String body = BODY_SERIALIZER.toJson(eventBody);

        pusher.post("/events", body); //Pusher instance
    }
```
