### ISSUE TITLE
How to set a socketId for the sender to avoid the sender receiving messages?

### ISSUE THREAD

**Issue by lidroba10** [pusher/pusher-http-java#69]
How to set a socketId for the sender to avoid the sender receiving messages?

**Comment by benw-pusher** [comment]
This process is documented at https://github.com/pusher/pusher-http-java#excluding-event-recipients. The socket id is provided to the client once a connection to Channels is established. For example, in the pusher-js library you might be able to use 

```        pusher.connection.bind('connected', function(socketIDObject) {
          socketId = socketIDObject.socket_id
          console.log(socketId);
          });```

to identify the socket ID. When your client makes a request to your api to send an event you would need to also include the socket ID, which you would then use in the linked function.
